// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qrwvdeljnqsevkvxwzvi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFyd3ZkZWxqbnFzZXZrdnh3enZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2MDEyOTEsImV4cCI6MjA2OTE3NzI5MX0.XQPDj_v-VQdiKmGB9QPaVnvtpDWBegIurR4AEhT0gq4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});